### ISSUE TITLE
Unable to connect to server

### ISSUE THREAD

**Issue by LothianB** [CommunityHoneyNetwork/CHN-Server#110]
Hi, thanks CHN.
I don't know if this is the correct place to ask for help.

This is my first installation and after trying on an EC2 instance and also a more local VKM VM I can connect to port 80 / 443 when I start chnserver. This on a NAT-ed Ubintu 18.04 VM (kvm)
``Hi, thanks CHN.

This is my first installation and after trying on an EC2 instance and also a more local VKM VM I can connect to port 80 / 443 when I start chnserver:
`
$ docker-compose ps
        Name                       Command               State                    Ports                  
---------------------------------------------------------------------------------------------------------
chnserver_chnserver_1   /usr/bin/runsvdir -P /etc/ ...   Up      0.0.0.0:443->443/tcp, 0.0.0.0:80->80/tcp
chnserver_hpfeeds_1     /usr/bin/runsvdir -P /etc/ ...   Up      0.0.0.0:10000->10000/tcp                
chnserver_mnemosyne_1   /usr/bin/runsvdir -P /etc/ ...   Up      8181/tcp                                
chnserver_mongodb_1     /usr/bin/runsvdir -P /etc/ ...   Up      27017/tcp                               
chnserver_redis_1       /usr/bin/runsvdir -P /etc/ ...   Up      6379/tcp``

`$ telnet localhost 80
Trying ::1...
Connected to localhost.
Escape character is '^]'.
Connection closed by foreign host.
`

I'm unsure if this is a docker or chn problem.

**Comment by LothianB** [comment]
I forgot to say that telneting to port 10000 is ok.

Thanks

**Comment by amerck** [comment]
Thanks for contacting us about this! I suspect I know what the issue is, but before I assume what is going on here, can you run the following command and paste the output? Thanks!

`docker-compose logs chnserver`

**Comment by LothianB** [comment]
Hi, thanks for the swift reply. Here you go:

$ docker-compose logs chnserver
Attaching to 

And nothing

Thanks

**Comment by LothianB** [comment]
Oops! sorry:

Attaching to chnserver_chnserver_1
chnserver_1  | + source /etc/default/chnserver
chnserver_1  | ++ DEBUG=false
chnserver_1  | ++ EMAIL=admin@localhost
chnserver_1  | ++ SERVER_BASE_URL=vubu150
chnserver_1  | ++ HONEYMAP_URL=
chnserver_1  | ++ REDIS_URL=redis://redis:6379
chnserver_1  | ++ MAIL_SERVER=127.0.0.1
chnserver_1  | ++ MAIL_PORT=25
chnserver_1  | ++ MAIL_TLS=y
chnserver_1  | ++ MAIL_SSL=y
chnserver_1  | ++ MAIL_USERNAME=
chnserver_1  | ++ MAIL_PASSWORD=
chnserver_1  | ++ DEFAULT_MAIL_SENDER=
chnserver_1  | ++ MONGODB_HOST=mongodb
chnserver_1  | ++ MONGODB_PORT=27017
chnserver_1  | ++ HPFEEDS_HOST=hpfeeds
chnserver_1  | ++ HPFEEDS_PORT=10000
chnserver_1  | ++ SUPERUSER_EMAIL=
chnserver_1  | ++ SUPERUSER_PASSWORD=
chnserver_1  | ++ SECRET_KEY=
chnserver_1  | ++ DEPLOY_KEY=
chnserver_1  | ++ CERTIFICATE_STRATEGY=CERTBOT
chnserver_1  | + set -o errexit
chnserver_1  | + set -o nounset
chnserver_1  | + trap 'exit 130' SIGINT
chnserver_1  | + trap 'exit 137' SIGKILL
chnserver_1  | + trap 'exit 143' SIGTERM
chnserver_1  | + PIDFILE=/var/run/nginx.pid
chnserver_1  | + SERVER_BASE_URL=vubu150
chnserver_1  | ++ awk -F/ '{print $3}'
chnserver_1  | ++ echo vubu150
chnserver_1  | + SERVER=
chnserver_1  | + [[ -f /var/run/nginx.pid ]]
chnserver_1  | + mkdir -p /var/log/nginx
chnserver_1  | + touch /var/log/nginx/error.log
chnserver_1  | ++ echo vubu150
chnserver_1  | ++ awk -F: '{print $1}'
chnserver_1  | + protocol=vubu150
chnserver_1  | + [[ vubu150 == \h\t\t\p ]]
chnserver_1  | + [[ '' == \l\o\c\a\l\h\o\s\t ]]
chnserver_1  | + [[ '' =~ ([0-9]{1,3}\.){3}[0-9]{1,3} ]]
chnserver_1  | + CERTIFICATE_STRATEGY=CERTBOT
chnserver_1  | + CERT_FILE=/tls/cert.pem
chnserver_1  | + KEY_FILE=/tls/key.pem
chnserver_1  | + case "${CERTIFICATE_STRATEGY}" in
chnserver_1  | + echo 'Using CERTBOT to manage certificate'
chnserver_1  | Using CERTBOT to manage certificate
chnserver_1  | + ACME_SERVER=https://acme-v02.api.letsencrypt.org/directory
chnserver_1  | + certbot certonly --standalone -n --register-unsafely-without-email --keep-until-expiring --agree-tos --domains --server=https://acme-v02.api.letsencrypt.org/directory
chnserver_1  | usage: 
chnserver_1  |   certbot [SUBCOMMAND] [options] [-d DOMAIN] [-d DOMAIN] ...
chnserver_1  | 
chnserver_1  | Certbot can obtain and install HTTPS/TLS/SSL certificates.  By default,
chnserver_1  | it will attempt to use a webserver both for obtaining and installing the
chnserver_1  | certificate. 
chnserver_1  | certbot: error: argument -d/--domains/--domain: expected one argument
chnserver_1  | + source /etc/default/chnserver
chnserver_1  | ++ DEBUG=false
chnserver_1  | ++ EMAIL=admin@localhost
chnserver_1  | ++ SERVER_BASE_URL=vubu150
chnserver_1  | ++ HONEYMAP_URL=
chnserver_1  | ++ REDIS_URL=redis://redis:6379
chnserver_1  | ++ MAIL_SERVER=127.0.0.1
chnserver_1  | ++ MAIL_PORT=25
chnserver_1  | ++ MAIL_TLS=y
chnserver_1  | ++ MAIL_SSL=y
chnserver_1  | ++ MAIL_USERNAME=
chnserver_1  | ++ MAIL_PASSWORD=
chnserver_1  | ++ DEFAULT_MAIL_SENDER=
chnserver_1  | ++ MONGODB_HOST=mongodb
chnserver_1  | ++ MONGODB_PORT=27017
chnserver_1  | ++ HPFEEDS_HOST=hpfeeds
chnserver_1  | ++ HPFEEDS_PORT=10000
chnserver_1  | ++ SUPERUSER_EMAIL=
chnserver_1  | ++ SUPERUSER_PASSWORD=
chnserver_1  | ++ SECRET_KEY=
chnserver_1  | ++ DEPLOY_KEY=
chnserver_1  | ++ CERTIFICATE_STRATEGY=CERTBOT
chnserver_1  | + set -o errexit
chnserver_1  | + set -o nounset
chnserver_1  | + trap 'exit 130' SIGINT
chnserver_1  | + trap 'exit 137' SIGKILL
chnserver_1  | + trap 'exit 143' SIGTERM
chnserver_1  | + PIDFILE=/var/run/nginx.pid
chnserver_1  | + SERVER_BASE_URL=vubu150
chnserver_1  | ++ awk -F/ '{print $3}'
chnserver_1  | ++ echo vubu150
chnserver_1  | + SERVER=
chnserver_1  | + [[ -f /var/run/nginx.pid ]]
chnserver_1  | + mkdir -p /var/log/nginx
chnserver_1  | + touch /var/log/nginx/error.log
chnserver_1  | ++ echo vubu150
chnserver_1  | ++ awk -F: '{print $1}'
chnserver_1  | + protocol=vubu150
chnserver_1  | + [[ vubu150 == \h\t\t\p ]]
chnserver_1  | + [[ '' == \l\o\c\a\l\h\o\s\t ]]
chnserver_1  | + [[ '' =~ ([0-9]{1,3}\.){3}[0-9]{1,3} ]]
chnserver_1  | + CERTIFICATE_STRATEGY=CERTBOT
chnserver_1  | + CERT_FILE=/tls/cert.pem
chnserver_1  | + KEY_FILE=/tls/key.pem
chnserver_1  | + case "${CERTIFICATE_STRATEGY}" in
chnserver_1  | + echo 'Using CERTBOT to manage certificate'
chnserver_1  | Using CERTBOT to manage certificate
chnserver_1  | + ACME_SERVER=https://acme-v02.api.letsencrypt.org/directory
chnserver_1  | + certbot certonly --standalone -n --register-unsafely-without-email --keep-until-expiring --agree-tos --domains --server=https://acme-v02.api.letsencrypt.org/directory
chnserver_1  | Traceback (most recent call last):
chnserver_1  |   File "/usr/local/bin/celery", line 11, in <module>
chnserver_1  |     sys.exit(main())
chnserver_1  |   File "/usr/local/lib/python2.7/dist-packages/celery/__main__.py", line 30, in main
chnserver_1  |     main()
chnserver_1  |   File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 81, in main
chnserver_1  |     cmd.execute_from_commandline(argv)
chnserver_1  |   File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 769, in execute_from_commandline
chnserver_1  |     super(CeleryCommand, self).execute_from_commandline(argv)))
chnserver_1  |   File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 305, in execute_from_commandline
chnserver_1  |     argv = self.setup_app_from_commandline(argv)
chnserver_1  |   File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 465, in setup_app_from_commandline
chnserver_1  |     self.app = self.find_app(app)
chnserver_1  |   File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 485, in find_app
chnserver_1  |     return find_app(app, symbol_by_name=self.symbol_by_name)
chnserver_1  |   File "/usr/local/lib/python2.7/dist-packages/celery/app/utils.py", line 229, in find_app
chnserver_1  |     sym = symbol_by_name(app, imp=imp)
chnserver_1  |   File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 488, in symbol_by_name
chnserver_1  |     return symbol_by_name(name, imp=imp)
chnserver_1  |   File "/usr/local/lib/python2.7/dist-packages/kombu/utils/__init__.py", line 96, in symbol_by_name
chnserver_1  |     module = imp(module_name, package=package, **kwargs)
chnserver_1  |   File "/usr/local/lib/python2.7/dist-packages/celery/utils/imports.py", line 101, in import_from_cwd
chnserver_1  |     return imp(module, package=package)
chnserver_1  |   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
chnserver_1  |     __import__(name)
chnserver_1  |   File "/opt/mhn/__init__.py", line 64, in <module>
chnserver_1  |     mhn.config['LOG_FILE_PATH'], maxBytes=10240, backupCount=5)
chnserver_1  |   File "/usr/lib/python2.7/logging/handlers.py", line 117, in __init__
chnserver_1  |     BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
chnserver_1  |   File "/usr/lib/python2.7/logging/handlers.py", line 64, in __init__
chnserver_1  |     logging.FileHandler.__init__(self, filename, mode, encoding, delay)
chnserver_1  |   File "/usr/lib/python2.7/logging/__init__.py", line 920, in __init__
chnserver_1  |     StreamHandler.__init__(self, self._open())
chnserver_1  |   File "/usr/lib/python2.7/logging/__init__.py", line 950, in _open
chnserver_1  |     stream = open(self.baseFilename, self.mode)
chnserver_1  | IOError: [Errno 13] Permission denied: '/var/log/mhn/mhn.log'
chnserver_1  | [2019-04-11 14:13:37,695: INFO/MainProcess] beat: Starting...
chnserver_1  | usage: 
chnserver_1  |   certbot [SUBCOMMAND] [options] [-d DOMAIN] [-d DOMAIN] ...
chnserver_1  | 
chnserver_1  | Certbot can obtain and install HTTPS/TLS/SSL certificates.  By default,
chnserver_1  | it will attempt to use a webserver both for obtaining and installing the
chnserver_1  | certificate. 
chnserver_1  | certbot: error: argument -d/--domains/--domain: expected one argument
chnserver_1  | Database already initialized
chnserver_1  | + source /etc/default/chnserver
chnserver_1  | ++ DEBUG=false
chnserver_1  | ++ EMAIL=admin@localhost
chnserver_1  | ++ SERVER_BASE_URL=vubu150
chnserver_1  | ++ HONEYMAP_URL=
chnserver_1  | ++ REDIS_URL=redis://redis:6379
chnserver_1  | ++ MAIL_SERVER=127.0.0.1
chnserver_1  | ++ MAIL_PORT=25
chnserver_1  | ++ MAIL_TLS=y
chnserver_1  | ++ MAIL_SSL=y
chnserver_1  | ++ MAIL_USERNAME=
chnserver_1  | ++ MAIL_PASSWORD=
chnserver_1  | ++ DEFAULT_MAIL_SENDER=
chnserver_1  | ++ MONGODB_HOST=mongodb
chnserver_1  | ++ MONGODB_PORT=27017
chnserver_1  | ++ HPFEEDS_HOST=hpfeeds
chnserver_1  | ++ HPFEEDS_PORT=10000
chnserver_1  | ++ SUPERUSER_EMAIL=
chnserver_1  | ++ SUPERUSER_PASSWORD=
chnserver_1  | ++ SECRET_KEY=
chnserver_1  | ++ DEPLOY_KEY=
chnserver_1  | ++ CERTIFICATE_STRATEGY=CERTBOT
chnserver_1  | + set -o errexit
chnserver_1  | + set -o nounset
chnserver_1  | + trap 'exit 130' SIGINT
chnserver_1  | + trap 'exit 137' SIGKILL
chnserver_1  | + trap 'exit 143' SIGTERM
chnserver_1  | + PIDFILE=/var/run/nginx.pid
chnserver_1  | + SERVER_BASE_URL=vubu150
chnserver_1  | ++ echo vubu150
chnserver_1  | ++ awk -F/ '{print $3}'
chnserver_1  | + SERVER=
chnserver_1  | + [[ -f /var/run/nginx.pid ]]
chnserver_1  | + mkdir -p /var/log/nginx
chnserver_1  | + touch /var/log/nginx/error.log
chnserver_1  | ++ echo vubu150
chnserver_1  | ++ awk -F: '{print $1}'
chnserver_1  | + protocol=vubu150
chnserver_1  | + [[ vubu150 == \h\t\t\p ]]
chnserver_1  | + [[ '' == \l\o\c\a\l\h\o\s\t ]]
chnserver_1  | + [[ '' =~ ([0-9]{1,3}\.){3}[0-9]{1,3} ]]
chnserver_1  | + CERTIFICATE_STRATEGY=CERTBOT
chnserver_1  | + CERT_FILE=/tls/cert.pem
chnserver_1  | + KEY_FILE=/tls/key.pem
chnserver_1  | + case "${CERTIFICATE_STRATEGY}" in
chnserver_1  | + echo 'Using CERTBOT to manage certificate'
chnserver_1  | + ACME_SERVER=https://acme-v02.api.letsencrypt.org/directory
chnserver_1  | Using CERTBOT to manage certificate
chnserver_1  | + certbot certonly --standalone -n --register-unsafely-without-email --keep-until-expiring --agree-tos --domains --server=https://acme-v02.api.letsencrypt.org/directory
chnserver_1  | 
chnserver_1  | *** Starting uWSGI 2.0.14 (64bit) on [Thu Apr 11 14:13:41 2019] ***
chnserver_1  | compiled with version: 7.3.0 on 22 February 2019 19:53:06
chnserver_1  | os: Linux-4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019
chnserver_1  | nodename: 4172ba440318
chnserver_1  | machine: x86_64
chnserver_1  | clock source: unix
chnserver_1  | detected number of CPU cores: 2
chnserver_1  | current working directory: /opt
chnserver_1  | detected binary path: /usr/local/bin/uwsgi
chnserver_1  | !!! no internal routing support, rebuild with pcre support !!!
chnserver_1  | uWSGI running as root, you can use --uid/--gid/--chroot options
chnserver_1  | *** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chnserver_1  | *** WARNING: you are running uWSGI without its master process manager ***
chnserver_1  | your memory page size is 4096 bytes
chnserver_1  | detected max file descriptor number: 1048576
chnserver_1  | lock engine: pthread robust mutexes
chnserver_1  | thunder lock: disabled (you can enable it with --thunder-lock)
chnserver_1  | uwsgi socket 0 bound to UNIX address /tmp/uwsgi.sock fd 3
chnserver_1  | Python version: 2.7.15rc1 (default, Nov 12 2018, 14:31:15)  [GCC 7.3.0]
chnserver_1  | *** Python threads support is disabled. You can enable it with --enable-threads ***
chnserver_1  | Python main interpreter initialized at 0x5648ad63c240
chnserver_1  | your server socket listen backlog is limited to 100 connections
chnserver_1  | your mercy for graceful operations on workers is 60 seconds
chnserver_1  | mapped 73624 bytes (71 KB) for 1 cores
chnserver_1  | *** Operational MODE: single process ***
chnserver_1  | usage: 
chnserver_1  |   certbot [SUBCOMMAND] [options] [-d DOMAIN] [-d DOMAIN] ...
chnserver_1  | 
chnserver_1  | Certbot can obtain and install HTTPS/TLS/SSL certificates.  By default,
chnserver_1  | it will attempt to use a webserver both for obtaining and installing the
chnserver_1  | certificate. 
chnserver_1  | certbot: error: argument -d/--domains/--domain: expected one argument
chnserver_1  | + source /etc/default/chnserver
chnserver_1  | ++ DEBUG=false
chnserver_1  | ++ EMAIL=admin@localhost
chnserver_1  | ++ SERVER_BASE_URL=vubu150
chnserver_1  | ++ HONEYMAP_URL=
chnserver_1  | ++ REDIS_URL=redis://redis:6379
chnserver_1  | ++ MAIL_SERVER=127.0.0.1
chnserver_1  | ++ MAIL_PORT=25
chnserver_1  | ++ MAIL_TLS=y
chnserver_1  | ++ MAIL_SSL=y
chnserver_1  | ++ MAIL_USERNAME=
chnserver_1  | ++ MAIL_PASSWORD=
chnserver_1  | ++ DEFAULT_MAIL_SENDER=
chnserver_1  | ++ MONGODB_HOST=mongodb
chnserver_1  | ++ MONGODB_PORT=27017
chnserver_1  | ++ HPFEEDS_HOST=hpfeeds
chnserver_1  | ++ HPFEEDS_PORT=10000
chnserver_1  | ++ SUPERUSER_EMAIL=
chnserver_1  | ++ SUPERUSER_PASSWORD=
chnserver_1  | ++ SECRET_KEY=
chnserver_1  | ++ DEPLOY_KEY=
chnserver_1  | ++ CERTIFICATE_STRATEGY=CERTBOT
chnserver_1  | + set -o errexit
chnserver_1  | + set -o nounset
chnserver_1  | + trap 'exit 130' SIGINT
chnserver_1  | + trap 'exit 137' SIGKILL
chnserver_1  | + trap 'exit 143' SIGTERM
chnserver_1  | + PIDFILE=/var/run/nginx.pid
chnserver_1  | + SERVER_BASE_URL=vubu150
chnserver_1  | ++ echo vubu150
chnserver_1  | ++ awk -F/ '{print $3}'
chnserver_1  | + SERVER=
chnserver_1  | + [[ -f /var/run/nginx.pid ]]
chnserver_1  | + mkdir -p /var/log/nginx
chnserver_1  | + touch /var/log/nginx/error.log
chnserver_1  | ++ awk -F: '{print $1}'
chnserver_1  | ++ echo vubu150
chnserver_1  | + protocol=vubu150
chnserver_1  | + [[ vubu150 == \h\t\t\p ]]
chnserver_1  | + [[ '' == \l\o\c\a\l\h\o\s\t ]]
chnserver_1  | + [[ '' =~ ([0-9]{1,3}\.){3}[0-9]{1,3} ]]
chnserver_1  | + CERTIFICATE_STRATEGY=CERTBOT
chnserver_1  | + CERT_FILE=/tls/cert.pem
chnserver_1  | + KEY_FILE=/tls/key.pem
chnserver_1  | + case "${CERTIFICATE_STRATEGY}" in
chnserver_1  | + echo 'Using CERTBOT to manage certificate'
chnserver_1  | Using CERTBOT to manage certificate
chnserver_1  | + ACME_SERVER=https://acme-v02.api.letsencrypt.org/directory
chnserver_1  | + certbot certonly --standalone -n --register-unsafely-without-email --keep-until-expiring --agree-tos --domains --server=https://acme-v02.api.letsencrypt.org/directory

**Comment by JesseBowling** [comment]
Hi @LothianB !

Based on the output listed here, it looks like the server is failing to start because the certbot/Let'sEncrypt bootstrap is failing. There are two issues here:

* SERVER_BASE_URL is not set to a FQDN; this should be set to "https://fully.qualified.domain.name" for your machine IF you want a real cert from Let'sEncrypt
* The CERTIFICATE_STRATEGY=CERTBOT will not work in a NAT environment, as the code relies on Let'sEncrypt being able to access the server, using the SERVER_BASE_URL, from their servers. This will not work with NAT

So to get you up and running in the NAT environment, you should probably change your CERTIFICATE_STRATEGY option to either SELF-SIGNED or BYO (see: https://communityhoneynetwork.readthedocs.io/en/stable/certificates/). Another option would be to set the SERVER_BASE_URL to the IP address, which will default the CERTIFICATE STRATEGY to SELF-SIGNED. 

Does this help?

**Comment by LothianB** [comment]
Hi and thanks for the reply,
I already tried changing the URL to the IP address of the server and I can't connect. I cant telnet to port 80 from the server (localhost) but not from another machine. Also, to test I spun up a wordpress server:
https://docs.docker.com/compose/wordpress/

**Comment by JesseBowling** [comment]
Hi @LothianB : Apologies for the delay. Are you still experiencing this issue? If not, can you try '127.0.0.1' rather than localhost?
