### ISSUE TITLE
Create a  build script for CHN-Server

### ISSUE THREAD

**Issue by JesseBowling** [CommunityHoneyNetwork/CHN-Server#111]
Create a basic repo that will populate default docker-compose and chnserver.sysconfig files into a directory.

* Bonus points: Guided "install" to help set options
* Bonus points: set up systemctl directories and startup script

**Comment by JesseBowling** [comment]
* also if no admin secret set, put a random one into chnserver.sysconfig

**Comment by drewstinnett** [comment]
Starting this process up here:

https://github.com/CommunityHoneyNetwork/chn-quickstart

Once the repo is downloaded, the docker-compose.yml needs to be updated with a real URL, then the compose up should do the rest...
