### ISSUE TITLE
When using self signed certs, new honeypots cannot register

### ISSUE THREAD

**Issue by JesseBowling** [CommunityHoneyNetwork/CHN-Server#114]
Even if the deploy command is adjusted, the internal registration process will use the scheme passed in. For self signed certs, validation fails and loops begin.

**Comment by ventz** [comment]
Running into this too.

**Comment by JesseBowling** [comment]
@amerck We discussed a number of ways to potentially solve this, but I believe we settled on passing an additional variable to the deploy script which would populate a sysconfig value, which would determine whether the honeypot would ignore certificate errors on registration. Convoluted at best, but preferable to simply ignoring validation errors blindly.

**Comment by JesseBowling** [comment]
Ultimately the solution should also resolve #112

**Comment by JesseBowling** [comment]
Resolving via branch resolve_114 on each honeypot
