### ISSUE TITLE
Examples for customizing cowrie.cfg or userdb.txt

### ISSUE THREAD

**Issue by adliwahid** [CommunityHoneyNetwork/CHN-Server#117]
Can I see an example of how the PERSONALITY variable is set in cowrie.sysconfig? I'd like to add my own userdb.txt & cowrie.cfg - tq

**Comment by JesseBowling** [comment]
Hi @adliwahid ! While I searched for the documentation I was *sure* I'd created, I found none...I will correct that shortly, but in the meantime:

The code the manages this starts here:
https://github.com/CommunityHoneyNetwork/cowrie/blob/master/cowrie.run.j2#L55

It's rather simple, but the idea is:

Look for a directory under the "/opt/personalities" folder in the container, specifically for a directory with the same name as the value specified in the `PERSONALITY` variable in `cowrie.sysconfig`. So by default only one other personality is shipped with the container, "aws-ubuntu16". Looking at this folder https://github.com/CommunityHoneyNetwork/cowrie/tree/master/personalities/aws-ubuntu16 (and the previous code) you can see that we simply iterate looking for files with the appropriate name and put those in place over the defaults. This means you don't have to provide all of the customizations, but whichever are present will take precedence. 

The tricky part is (and the reason I haven't pushed this further) is that these files ship in the container, so if you want something custom you have to 1) get the files to the host with which will run the container and 2) volume map them into the container. This would mean modifying both the `docker-compose` as well as the `cowrie.sysconfig` files. 

For a more concrete example: let's say I want to include a userdb.txt and cowrie.cfg file in a personality called 'sneakycowrie'. I would make the following changes:

```
<snip>
    volumes:
      - ./cowrie.sysconfig:/etc/default/cowrie
      - ./cowrie:/etc/cowrie
      - ./sneakycowrie:/opt/personalities/sneakycowrie
<snip>
```
and then:
```
# A specific "personality" directory for the Cowrie honeypot may be specified
# here. These directories can include custom fs.pickle, cowrie.cfg, txtcmds and
# userdb.txt files which can influence the attractiveness of the honeypot.
PERSONALITY="sneakycowrie"
```
You should then be able to `docker-compose down` and `docker-compose up -d` at this point and the personality should take effect. 

Let me know if that answers your question and helps out! Regardless I'll be documenting this shortly in the latest documentation. :)

**Comment by JesseBowling** [comment]
I'd also appreciate any feedback on this section @adliwahid:

https://communityhoneynetwork.readthedocs.io/en/latest/cowrie/#adding-a-custom-cowrie-personality

**Comment by adliwahid** [comment]
Hi Jesse - thanks for the extensive answer. I'll have a go at it and check out the documentation - cheers :-)

**Comment by JesseBowling** [comment]
Going to assume this worked out; if not, please let me know and I'll re-open!

Cheers,

Jesse
