### ISSUE TITLE
Have mongodb store the Country of an IP

### ISSUE THREAD

**Issue by robinlennox** [CommunityHoneyNetwork/CHN-Server#127]
This would be useful to know:
- if the Country that the IP belongs to changes over time 
- it would save writing code to do a point in time lookup of the IPs Country.

**Comment by JesseBowling** [comment]
Hi @robinlennox !

sorry for the long delay. I'm closing this for now, but if you're still using CHN and would find this feature useful, please do open a new issue! 

Cheers
