### ISSUE TITLE
chnserver port not 443

### ISSUE THREAD

**Issue by arcgreen90** [CommunityHoneyNetwork/CHN-Server#136]
I'm curious if I can change the docker-compose.yml for the chnserver to cause the server to listen on a port besides 443.

**Comment by JesseBowling** [comment]
Hi @arcgreen90 ,

So currently you can make this work, however it would break the logic used to generate LetsEncrypt certificates. You can use self-signed or BYO and it appears the proper things happen downstream.

To do this you will need to set both:

SERVER_BASE_URL in chnserver.sysconfig to reference the port, i.e.:

```
SERVER_BASE_URL="https://site.tld:5000"
```
Appropriate port translation in docker-compose.yml, i.e.:
```
    ports:
      - 80:80
      - 5000:443
```
I'll file a bug about the port issue with the letsencrypt bootstrap code.

Does this help? I'll close for now, but please comment and I can re-open if you need anything else on this!

**Comment by JesseBowling** [comment]
A fix is in master via:

https://github.com/CommunityHoneyNetwork/CHN-Server/issues/137

this will make it into the next cut of 1.8-pre, and of course 1.8 when it's final. Thanks for the question!
