### ISSUE TITLE
Production Consideration - CHN-Server install failing in isolated enclave

### ISSUE THREAD

**Issue by StrangerDanger0-o** [CommunityHoneyNetwork/CHN-Server#144]
Hey All - be gentle 1st time github posting.

I am running into an issue where generateconfig.py is failing to generate a config  

https://github.com/CommunityHoneyNetwork/CHN-Server/blob/ecd105572811c4b2c4582e5cd6db75df72d62c83/generateconfig.py#L27

The server I am installing on is in a secure enclave that is not capable of internet access.

**This raises the below error:**
chnserver_1  | Traceback (most recent call last):
chnserver_1  |   File "/usr/local/bin/celery", line 11, in <module>
chnserver_1  |     sys.exit(main())
chnserver_1  |   File "/usr/local/lib/python2.7/dist-packages/celery/__main__.py", line 30, in main
chnserver_1  |     main()
chnserver_1  |   File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 81, in main
chnserver_1  |     cmd.execute_from_commandline(argv)
chnserver_1  |   File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 769, in execute_from_commandline
chnserver_1  |     super(CeleryCommand, self).execute_from_commandline(argv)))
chnserver_1  |   File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 305, in execute_from_commandline
chnserver_1  |     argv = self.setup_app_from_commandline(argv)
chnserver_1  |   File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 465, in setup_app_from_commandline
chnserver_1  |     self.app = self.find_app(app)
chnserver_1  |   File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 485, in find_app
chnserver_1  |     return find_app(app, symbol_by_name=self.symbol_by_name)
chnserver_1  |   File "/usr/local/lib/python2.7/dist-packages/celery/app/utils.py", line 229, in find_app
chnserver_1  |     sym = symbol_by_name(app, imp=imp)
chnserver_1  |   File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 488, in symbol_by_name
chnserver_1  |     return symbol_by_name(name, imp=imp)
chnserver_1  |   File "/usr/local/lib/python2.7/dist-packages/kombu/utils/__init__.py", line 96, in symbol_by_name
chnserver_1  |     module = imp(module_name, package=package, **kwargs)
chnserver_1  |   File "/usr/local/lib/python2.7/dist-packages/celery/utils/imports.py", line 101, in import_from_cwd
chnserver_1  |     return imp(module, package=package)
chnserver_1  |   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
chnserver_1  |     __import__(name)
chnserver_1  |   File "/opt/mhn/__init__.py", line 27, in <module>
chnserver_1  |     mhn.config.from_object('config')
chnserver_1  |   File "/usr/local/lib/python2.7/dist-packages/flask/config.py", line 170, in from_object
chnserver_1  |     obj = import_string(obj)
chnserver_1  |   File "/usr/local/lib/python2.7/dist-packages/werkzeug/utils.py", line 564, in import_string
chnserver_1  |     ImportStringError, ImportStringError(import_name, e), sys.exc_info()[2]
chnserver_1  |   File "/usr/local/lib/python2.7/dist-packages/werkzeug/utils.py", line 547, in import_string
chnserver_1  |     __import__(import_name)
chnserver_1  | werkzeug.utils.ImportStringError: import_string() failed for 'config'. Possible reasons are:
chnserver_1  |
chnserver_1  | - missing __init__.py in a package;
chnserver_1  | - package or module path not included in sys.path;
chnserver_1  | - duplicated package or module name taking precedence in sys.path;
chnserver_1  | - missing module, class, function or variable;
chnserver_1  |
chnserver_1  | Debugged import:
chnserver_1  |
chnserver_1  | - 'config' not found.
chnserver_1  |
chnserver_1  | Original exception:
chnserver_1  |
chnserver_1  | ImportError: No module named config

I thought perhaps attempting to wrap in a try/except or on fail prompt for input - but wouldn't presume to try and correct the issue myself.

Is this something that could be changed?

Thanks for any insight.

**Comment by JesseBowling** [comment]
Hi! This is certainly something that can be fixed, and has been fixed in master. You should see this make it out to production in version 1.9, which should be relatively soon.

https://github.com/CommunityHoneyNetwork/CHN-Server/blob/master/generateconfig.py#L25
