### ISSUE TITLE
The container of chnserver startup failed due to ImportError

### ISSUE THREAD

**Issue by ADeeeee** [CommunityHoneyNetwork/CHN-Server#149]
Server: Ubuntu 18.04.4 LTS
docker: version 19.03.6, build 369ce74a3c

The chnserver doesn't work and keep printing this in log:
> Traceback (most recent call last):
>   File "./mhn/__init__.py", line 5, in <module>
>     from flask_security import Security, SQLAlchemyUserDatastore
>   File "/usr/local/lib/python2.7/dist-packages/flask_security/__init__.py", line 13, in <module>
>     from .core import Security, RoleMixin, UserMixin, AnonymousUser, current_user
>   File "/usr/local/lib/python2.7/dist-packages/flask_security/core.py", line 28, in <module>
>     from .forms import ChangePasswordForm, ConfirmRegisterForm, \
>   File "/usr/local/lib/python2.7/dist-packages/flask_security/forms.py", line 17, in <module>
>     from flask_wtf import FlaskForm as BaseForm
>   File "/usr/local/lib/python2.7/dist-packages/flask_wtf/__init__.py", line 17, in <module>
>     from .recaptcha import *
>   File "/usr/local/lib/python2.7/dist-packages/flask_wtf/recaptcha/__init__.py", line 2, in <module>
>     from .fields import *
>   File "/usr/local/lib/python2.7/dist-packages/flask_wtf/recaptcha/fields.py", line 3, in <module>
>     from . import widgets
>   File "/usr/local/lib/python2.7/dist-packages/flask_wtf/recaptcha/widgets.py", line 5, in <module>
>     from werkzeug import url_encode
> ImportError: cannot import name url_encode

It seems relatived with https://github.com/lepture/flask-wtf/issues/377

The issue could be solved by:
1. Change the import method in python (Not sure where the code is yet, ref: https://github.com/awslabs/scale-out-computing-on-aws/issues/2)
2. Install older version of werkzeug as a workaround (add "werkzeug==0.15.6" in requirement.txt before you build the image), which I tried and worked with current master branch.

How do I fix it in the right way instead of the workaround?

Reference:
https://werkzeug.palletsprojects.com/en/master/changes/#version-1-0-0

**Comment by JesseBowling** [comment]
Hi,

We noticed this earlier as well. We are working to correct this is another branch, as per of a larger effort to migrate everything to python 3. 

Given that the timeline for those changes (which will release in 1.9) is not firm as of yet, I’ll ask @breakfastdub if he can share at least the relevant code for this particular issue. 

@breakfastdub can you patch master for just this issue by chance?

**Comment by JesseBowling** [comment]
Hi,

Closing this issue due to lack of update; please feel free to open a new issue if this remains a problem!

Please do try the latest version (1.9) or a build from master branch. :)
