### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by s4m0ur41** [CommunityHoneyNetwork/CHN-Server#152]
Hi there,

I received the following error message executing ./guided_docker_compose.py

Traceback (most recent call last):
File "./guided_docker_compose.py", line 6, in <module>
import validators

Should I comment this line ?

#!/usr/bin/env python3
import sys
import socket
import os
import argparse
**import validators**
import secrets
import string
from urllib.parse import urlparse

Thank you very much in advance for repliers.
Have a nice day.

**Comment by JesseBowling** [comment]
Hi @s4m0ur41:

Actually it would be best to install the pre-requisite python package `validators`. This can be accomplished by:

`pip3 install -r requirements.txt`

which will install all prerequisite python packages (currently only validators) or simply:
 
`pip3 install validators`

Does this help?

Please keep feedback and issues coming! :)

**Comment by s4m0ur41** [comment]
Yes it solved this part. Thank you very much.
Now I have this for the docker part with : docker-compose up -d 

ERROR: Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?
If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.

I tried docker-compose start and :

Starting mongodb        ... done
Starting hpfeeds        ... done
Starting hpfeeds-logger ... done
Starting redis          ... done
Starting chnserver      ... done
Starting mnemosyne      ... done
ERROR: No containers to start

then I tried again docker-compose up -d but same error message firstly stated.
Sorry about all questions I am kind of beginner here. I appreciated your patience

**Comment by JesseBowling** [comment]
Hi! No problem. Those messages usually indicate that either docker isn't running, or your user is not in the docker group allowed to run containers without sudo access. I would suggest running:

`sudo systemctl status docker` to ensure docker is running, or start it if it's not.

If Docker is running, try running `sudo docker-compose up -d` to start up the containers. If you want the user to always be able to start Docker containers without `sudo` you can add them to the docker group. Usually this would be something like `usermod -a -G docker ${USER)`

**Comment by s4m0ur41** [comment]
Thak you again for your answer and your help. 
Seems to be active but with errors ?

● docker.service - Docker Application Container Engine
Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
Active: active (running) since Mon 2020-03-02 09:27:54 EST; 8h ago
Docs: https://docs.docker.com
Main PID: 3204 (dockerd)
Tasks: 11
CGroup: /system.slice/docker.service
└─3204 /usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock

Mar 02 09:27:51 HoneyBaby dockerd[3204]: time="2020-03-02T09:27:51.576800006-05:00" level=warning msg="Your kernel does not support cgroup rt period"
Mar 02 09:27:51 HoneyBaby dockerd[3204]: time="2020-03-02T09:27:51.576826484-05:00" level=warning msg="Your kernel does not support cgroup rt runtime"
Mar 02 09:27:51 HoneyBaby dockerd[3204]: time="2020-03-02T09:27:51.577552085-05:00" level=info msg="Loading containers: start."
Mar 02 09:27:52 HoneyBaby dockerd[3204]: time="2020-03-02T09:27:52.242912681-05:00" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP
Mar 02 09:27:52 HoneyBaby dockerd[3204]: time="2020-03-02T09:27:52.670906136-05:00" level=info msg="Loading containers: done."
Mar 02 09:27:52 HoneyBaby dockerd[3204]: time="2020-03-02T09:27:52.693039108-05:00" level=warning msg="failed to retrieve runc version: unknown output format: runc version spec: 1.0.1-dev\n"
Mar 02 09:27:53 HoneyBaby dockerd[3204]: time="2020-03-02T09:27:53.650076056-05:00" level=info msg="Docker daemon" commit=2d0083d graphdriver(s)=overlay2 version=18.09.7
Mar 02 09:27:53 HoneyBaby dockerd[3204]: time="2020-03-02T09:27:53.650315555-05:00" level=info msg="Daemon has completed initialization"
Mar 02 09:27:54 HoneyBaby systemd[1]: Started Docker Application Container Engine.
Mar 02 09:27:54 HoneyBaby dockerd[3204]: time="2020-03-02T09:27:54.117193149-05:00" level=info msg="API listen on /var/run/docker.sock"

Same error message with docker-compose up -d command.
I feel so unusefull :(

**Comment by JesseBowling** [comment]
Hi @s4m0ur41 : Can you confirm this is still an issue for you? The above logs appear to have multiple runs installed...Can you provide an output just from `docker-compose up` run?

**Comment by JesseBowling** [comment]
Hi,

Closing this issue due to lack of update; please feel free to open a new issue if this remains a problem!
