### ISSUE TITLE
Error related to Redis

### ISSUE THREAD

**Issue by adliwahid** [CommunityHoneyNetwork/CHN-Server#157]
In the documentation it was noted that 
"If you chose not to run hpfeeds-cif or hpfeeds-bhr, the redis container can be omitted" 
(https://communityhoneynetwork.readthedocs.io/en/stable/serverinstall/#deploying-the-server-manually) 

However, in the logs I see error messages of CHN is trying to connect to the redis server. 

chnserver_1       | [2020-04-18 03:17:58,549: ERROR/MainProcess] beat: Connection e
rror: . Trying again in 32.0 seconds...
chnserver_1       | [2020-04-18 03:18:00,528: ERROR/MainProcess] consumer: Cannot c
onnect to redis://localhost:6379//: .
chnserver_1       | Trying again in 32.00 seconds...
chnserver_1       | 
chnserver_1       | [2020-04-18 03:18:30,583: ERROR/MainProcess] beat: Connection e

I am not running hpfeeds-bir nor hpfeeds-bhr.  I started redis at some point and still see that error. Everything is working fine but I just can't pin point what is generating or causing it.

**Comment by amerck** [comment]
Thanks for reporting this issue.

When you get a moment, can you run 'docker ps' and send the line for the chnserver container? Thanks!

**Comment by adliwahid** [comment]
421a98274308        stingar/chn-server:1.8       "/usr/bin/runsvdir -…"   3 weeks ago         Up 3 weeks          0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   chnserver_chnserver_1

**Comment by JesseBowling** [comment]
Hi @adliwahid !

Sorry for the issues. That documentation is...correct in version 1.9 which we are about to make official. You can try out 1.9 using the 'latest' documentation version:

https://communityhoneynetwork.readthedocs.io/en/latest/prerequisite/

This should do the right thing with redis. Let me know if you find that not to be the case, or if you find other issues.

**Comment by JesseBowling** [comment]
Hi,

Closing this issue due to lack of update; please feel free to open a new issue if this remains a problem!
