### ISSUE TITLE
manifest for stingar/dionaea-arm:1.9 not found

### ISSUE THREAD

**Issue by ariddi7** [CommunityHoneyNetwork/CHN-Server#160]
When trying to deploy Dionaea (intel/arm) from the deploy command produces the following error:
ERROR: manifest for stingar/dionaea-arm:1.9 not found

Other honeypots like cowrie seem to work.

**Comment by JesseBowling** [comment]
Hi,

There is now a dionaea-arm image available!

Sorry for the issue!
