### ISSUE TITLE
Can't connect to CHN Server

### ISSUE THREAD

**Issue by anonuser78** [CommunityHoneyNetwork/CHN-Server#161]
The attacks are not getting logged in the server, can you please assist?

**Comment by JesseBowling** [comment]
I'm afraid there's not enough information in this issue to assist. Closing for now, but please feel free to open a new issue that includes information such as:

* Method of installation (quickstart, manual)
* Version used (built from master, v1.9, etc.)
* Honeypots deployed (cowrie, dionaea, etc.)
* specific steps to recreate the issue.

Without this information we're unable to begin troubleshooting such an issue.
