### ISSUE TITLE
Celery beat pid file is not cleaned up

### ISSUE THREAD

**Issue by clcollins** [CommunityHoneyNetwork/CHN-Server#17]
With a docker-compose/docker build, the Celery beat service fails to restart when the service is restarted because the pid file is never cleaned up:

```
chnserver_1  | ERROR: Pidfile (celerybeat.pid) already exists.
chnserver_1  | Seems we're already running? (pid: 13)
```

**Comment by kujosHeist** [comment]
I also have this issue, is there a way around this other than manual delete?

**Comment by tzvika-m-ironsrc** [comment]
@clcollins did you find a solution?

**Comment by clcollins** [comment]
@tzvika-m-ironsrc: i added a check in the init script to remove the pidfile if it existed in https://github.com/CommunityHoneyNetwork/CHN-Server/commit/a0a57f038d5dd86dfae96db20b5611236fa3feac.  You should be able to get that change if you grab any of the latest releases.
