### ISSUE TITLE
Cowrie TTY Logs

### ISSUE THREAD

**Issue by destructiveresearchlabs** [CommunityHoneyNetwork/CHN-Server#174]
Where are the playlog files (tty) located for the Cowrie honeypot with a deployed CHN Server?
Didn't find any playlog files located in /opt/cowrie/var/lib/cowrie/tty or any specifics regarding this in the documentation. Are playlog files generated with a deployment of CHN Server?

**Comment by destructiveresearchlabs** [comment]
Resolved.

**Comment by NitescuLucian** [comment]
how was this resolved? what is the location?
