### ISSUE TITLE
config.py persistence; or able to be run multiple times

### ISSUE THREAD

**Issue by clcollins** [CommunityHoneyNetwork/CHN-Server#2]
The config.py file sets up default config info for the server.  This needs to be made persistent inside containers, or the script needs to be adjusted to be able to run multiple times without issue.

Some potential problems are the username/password fields.  What happens if they change?  Or if the password info is changed in the db?

**Comment by amerck** [comment]
Commit 152716a400b1558c8451f955c5e5fdcb639c73e1 addresses the issue of usernames/passwords changing and sensors deregistering when the container is restarted. However, I still consider this an issue, as the deploy key is stored in the config file and not the database, and will be modified when the script is rerun. I propose moving the deploy key into the database as well. 

We may want to consider taking care of this at the same time that we move user and sensor data to from sqlite to mongodb.

**Comment by JesseBowling** [comment]
Resolved some time in the distant past...
