### ISSUE TITLE
Remove dependency on evnet

### ISSUE THREAD

**Issue by JesseBowling** [CommunityHoneyNetwork/CHN-Server#24]
Hi,

The evnet project appears to be abandoned (last commit 2013). It would be best to remove dependency on evnet in all code.

**Comment by clcollins** [comment]
Indeed.  

I've temporarily changed it to reference a local fork, [https://github.com/CommunityHoneyNetwork/evnet](https://github.com/CommunityHoneyNetwork/evnet), and changed the forked version of evnet to reference https, so our build works now.  

But, yeah, it's stupid for us to carry a fork for literally a single character diff.

+1 to removing [rep/evnet](https://github.com/rep/evnet) as an upstream dependency.  5 yrs inactivity is probably long enough to call it a dead project.

**Comment by JesseBowling** [comment]
Confirmed that evnet is a dead project with Project Honeynet folks. We'll leave this in now, and do something new in 2.0.
