### ISSUE TITLE
Service 'hpbuilds' failed to build:

### ISSUE THREAD

**Issue by dsolowitz** [CommunityHoneyNetwork/CHN-Server#34]
Following the quick start guide while building the docker images for the containers that make up the server (per instruction), the following error is reported. "ERROR: Service 'hpfeeds' failed to build: The command '/bin/sh -c ansible-playbook /opt/${playbook}' returned a non-zero code: 2"
<img width="1418" alt="screen shot 2018-02-06 at 3 08 09 pm" src="https://user-images.githubusercontent.com/25187043/35881693-a652b6de-0b4f-11e8-80be-d4ebb4b2d996.png">

This was confirmed when I typed command "docker-compose ps" to verify if the server was running.

Running this via ssh on Ubuntu 16.04

**Comment by breakfastdub** [comment]
It looks like evnet is no longer available via pypi / pip...

We'll look at running our own repo of this package until we can replace hpfeeds.

**Comment by clcollins** [comment]
Fixed by https://github.com/CommunityHoneyNetwork/hpfeeds/pull/12

**Comment by breakfastdub** [comment]
This issue should be resolved as of CommunityHoneyNetwork/hpfeeds#12. hpfeeds. now builds pyev from source using pip.
