### ISSUE TITLE
Ability to exclude devices by IP address from connecting to honeypot

### ISSUE THREAD

**Issue by JesseBowling** [CommunityHoneyNetwork/CHN-Server#39]
Use case is for "friendly" network scanners to either be prevented from connecting to the service or not include those network scanners in the resulting honeypot data.

**Comment by clcollins** [comment]
In my opinion, I would say we allow the connection and log it, but allow a way to filter them from the results when viewing. 

More data > Less data

Heh, see what I did there?

**Comment by kraigu** [comment]
> In my opinion, I would say we allow the connection and log it, but allow a way to filter them from the results when viewing.

I like this idea.

> More data > Less data

I don't know about that, but it definitely strikes me as easier to manage. Unless you renumber a scanner.
