### ISSUE TITLE
Update Geo info databases to use new db format

### ISSUE THREAD

**Issue by clcollins** [CommunityHoneyNetwork/CHN-Server#4]
GeoLiteCity.dat and GeoIPASNum.dat files from https://dev.maxmind.com/geoip/legacy/geolite/ are used by the Collector_v2.py file. MaxMind lists them on the website for download, but they are "legacy" and have been replaced with .mmdb database format.  

Should we consider updating to that format?  The new format also has .csv files available, if we want to go with a standard (if .mmdb is not a standard).

**Comment by JesseBowling** [comment]
I agree this would be good to update, but I'm not finding the mentioned file anywhere in the current images...Was this whole section already removed?

**Comment by JesseBowling** [comment]
Will close for now and revist in 2.0
