### ISSUE TITLE
Clear/reset data for specific sensors

### ISSUE THREAD

**Issue by JesseBowling** [CommunityHoneyNetwork/CHN-Server#40]
It would be useful to be able to clear data from specific sensors, with a use case being on the setup of a sensor, testing it with a connection, and then wanting that data cleared out.

**Comment by JesseBowling** [comment]
Should be in next tagged release

**Comment by amerck** [comment]
Fixed with commit 05587fc3ebc40c603fdea419c8db3f985fa7e4c7
