### ISSUE TITLE
Documentation on automatically starting server and honeypots

### ISSUE THREAD

**Issue by JesseBowling** [CommunityHoneyNetwork/CHN-Server#44]
I would love to see some documentation on how to ensure my CHN server and individual honeypots start automatically after a reboot of the host VM (so, presuming not using K8s, etc.).

**Comment by clcollins** [comment]
`--restart=always` as a flag to the docker cli, or `restart: always` in a docker-compose.yml

* https://docs.docker.com/engine/reference/commandline/run/#restart-policies---restart
* https://docs.docker.com/compose/compose-file/#restart

**Comment by JesseBowling** [comment]
@amerck @clcollins Thoughts on whether `restart: always` should be in the example docker-compose.yml files for each honeypot or simply noted in the documentation?

**Comment by clcollins** [comment]
My gut reaction is to say we do *not* want it for "example" documentation.  If someone's just playing with it, perhaps the containers should not default to being on.  This is probably more of a "do this in production" notice or something?  I would not consider any of our docs as "you should do this in prod".

**Comment by kraigu** [comment]
I'd definitely appreciate seeing "here's the quick start with dev-type stuff, but when you want this for reals... make these other changes."

**Comment by JesseBowling** [comment]
This is currently here:

https://communityhoneynetwork.readthedocs.io/en/latest/prod_security/#restart-on-boot

and will eventually flow to stable
