### ISSUE TITLE
sqlalchemy OperationalError when reseting default password

### ISSUE THREAD

**Issue by whh8b** [CommunityHoneyNetwork/CHN-Server#48]
Hello!

What an amazing quick start guide you've written! Everything is going great. However, when I reset the default password, 50% of the time I get the following error:

```
sqlalchemy.exc.OperationalError: (pysqlite2.dbapi2.OperationalError) database is locked [SQL: u'UPDATE user SET password=? WHERE user.id = ?'] [parameters: ('$2b$12$2On1qFmmd.ytyOXPdaYgR.j48T4K.JhtI9JZewpnRZNG8sc3Sjl9i', 1)] (Background on this error at: http://sqlalche.me/e/e3q8)
```

I am happy to provide additional information. Thanks again for the software and the nice guide to get started!

**Comment by JesseBowling** [comment]
Hi Will,

Are you by chance changing the password as part of an automation script? When you say this happens 50% of the time, is this a single instance which is being reset serially (i.e., one machine, password reset a number of times) or across multiple instances the failure rate is 50% (i.e., out of 4 machines attempting to be reset, only 2 are successful)?

Put another way, are failures persistent (i.e. unable to ever change the password for an instance once it's in this state)?

Generally the SQLite database is rarely used as part of continuous operation, so answers to the above questions would be greatly appreciated!

Cheers,

Jesse

**Comment by JesseBowling** [comment]
Hi @whh8b , any chance you can provide some more detail as requested above?

Thanks in advance!

Cheers,

Jesse

**Comment by JesseBowling** [comment]
I'll assume this is not an ongoing issue and close this for now...Please re-open if it continues to be a problem!
