### ISSUE TITLE
Change authentication from token based to TLS

### ISSUE THREAD

**Issue by drewstinnett** [CommunityHoneyNetwork/CHN-Server#50]
Because token based authentication has introduced some pain points, and to make deployment in k8s more integrated, we are planning on converting the authentication method to TLS.

**Comment by clcollins** [comment]
We should document how to use [cfssl](https://github.com/cloudflare/cfssl) for generating a CA and certificates for servers and clients.  This a a pretty well-supported and widely-used Go app created by Cloudflare.  It's used by the etcd community, for example, and other Kubernetes folks.

**Comment by kraigu** [comment]
If this is authentication between a honeypot client and the CHN server (which I think it is) then describing how to do things with bog standard openssl would be nice too. (I'm willing to work on that piece, once there's code to work against.) I assume it won't be radically different from cfssl though.

**Comment by drewstinnett** [comment]
Thanks @clcollins and @kraigu!  The cfssl bits will make it easier to script, but I'll include some docs on the normal OpenSSL bits too.  @kraigu all help is appreciated, thank you!

**Comment by JesseBowling** [comment]
Will address in 2.0.

Closing wontfix for this version.
