### ISSUE TITLE
Charts are partially broken

### ISSUE THREAD

**Issue by kraigu** [CommunityHoneyNetwork/CHN-Server#66]
Fresh 1.5 install, some of the charts seem broken.
Kippo/Cowrie Top Attackers works, but the other three hang; at a glance, they're trying to read some JS from kozea.github.io, which 404's.

I'm reasonably certain this has worked in the past, so presumably that github.io page disappeared at some point in the last month or two.

**Comment by JesseBowling** [comment]
Hi @kraigu,

Would you test on a current version? I'm not able to reproduce this at the moment.

**Comment by kraigu** [comment]
Installed latest on a fresh VM/docker container. No data since I'm not sending it any, but the charts do at least load. Since I think you're doing a full code rewrite for 2.x, it doesn't seem to me that this one's worth pursuing, I don't care *that* much about generating graphs on my current production. :)
